# params of reproduction
seed: 0

# params of dataset
dataset: "Digit"
data_root: "data/"
transform_type: "simple"
all_use: True

# params of DataLoader
samples_per_gpu: 64  # batch_size
samples_per_gpu_test: 64
workers_per_gpu: 4  # num_workers

# params of optimizer
# optimizer:
#   type: "Adam"
#   lr: 0.001
#   weight_decay: 0.0005
optimizer:
  type: "SGD"
  lr: 0.01
  weight_decay: 0.0005
  momentum: 0.9
  nesterov: True

# params of learning rate scheduler
lr_scheduler:
  type: "InvLR"
  gamma: 0.0003
  power: 0.75
# lr_scheduler:
#   type: "InvLR"
#   gamma: 10
#   power: 0.75
#   maxp: 2811

# params of training
loops: 50
max_epochs: 2
warmup_epochs: 1

# params of checkpoint and logging
# checkpoint: "log/20201211_192737/best_model.pth.tar"
save_interval: 500  # save checkpoint per n iterations
# test_interval: 500  # test per n iterations
test_interval_epoch: 1.0  # test per n epochs
log_interval: 50  # log infos per n iterations

# method-specified params
categorial_sample: True
use_val: False
thr: 0.9
quad_k: 1.0
pos_end: 0.5
k_tao: 1.0
pow: 1.0
len_buffer: 100
coeff_lossGD: 0.0
